spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: <host>
    port: <port>
    username: <user>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    templates:
      path: template

logging:
  level:
    org:
      hibernate:
        type: trace
